# Generated by Django 6.1.1 on 2026-09-19 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_menuitemingredient_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
